services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - orchestrator
    networks:
      - nexus-net

  orchestrator:
    build: ./orchestrator
    env_file:
      - .env
      - .env.example
    ports:
      # Exposes container port 8000 to host port 8001
      - "8001:8000"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - RAG_SERVICE_URL=http://rag_service:8002
      - CORS_ORIGINS=http://localhost:3000
    restart: always
    volumes:
      - ./database:/app/database # Persists the SQLite DB
    networks:
      - nexus-net
    depends_on:
      - rag_service

  rag_service:
    build: ./rag_service
    env_file:
      - .env
      - .env.example
    restart: always
    volumes:
      - ./database/chroma_db:/app/chroma_db # Persists the vector store
    ports:
      - "8002:8002"
    networks:
      - nexus-net

networks:
  nexus-net:
    driver: bridge